# Generated by Django 5.1.4 on 2024-12-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0003_alter_genre_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='performers/photos')),
                ('nationality', models.CharField(blank=True, choices=[('br', 'Brasileiro'), ('us', 'Americano'), ('uk', 'Britânico'), ('fr', 'Francês'), ('it', 'Italiano'), ('jp', 'Japonês'), ('cn', 'Chinês'), ('ru', 'Russo'), ('de', 'Alemão'), ('es', 'Espanhol'), ('ar', 'Argentino'), ('mx', 'Mexicano'), ('co', 'Colombiano'), ('pe', 'Peruano'), ('cl', 'Chileno'), ('ve', 'Venezuelano'), ('ec', 'Equatoriano'), ('bo', 'Boliviano'), ('py', 'Paraguaio'), ('uy', 'Uruguai)'), ('other', 'Outro')], max_length=100, null=True)),
                ('genre', models.ManyToManyField(to='genres.genre')),
            ],
        ),
    ]
