# Generated by Django 5.1.4 on 2024-12-24 13:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musics', '0002_alter_music_performers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Avaliação não pode ser inferior a 0 estrelas.'), django.core.validators.MaxValueValidator(5, 'Avaliação não pode ser superior a 5 estrelas.')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='musics.music')),
            ],
        ),
    ]
