# Generated by Django 5.1.4 on 2024-12-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0003_alter_genre_options'),
        ('performers', '0002_alter_performer_image_alter_performer_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('album', models.CharField(blank=True, max_length=300, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('ratting', models.FloatField(blank=True, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musics', to='genres.genre')),
                ('performers', models.ManyToManyField(blank=True, null=True, related_name='musics', to='performers.performer')),
            ],
        ),
    ]
