# Generated by Django 5.1.4 on 2024-12-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
        ('performers', '0002_alter_performer_image_alter_performer_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='performers',
            field=models.ManyToManyField(blank=True, related_name='musics', to='performers.performer'),
        ),
    ]
