# Generated by Django 5.1.4 on 2024-12-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_alter_music_performers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='ratting',
        ),
    ]
